runtime: nodejs20

instance_class: F1

env_variables:
  # These are defaults. Real DB credentials should come from Secret Manager
  # or be overridden in the App Engine dashboard.
  NODE_ENV: 'production'
  PORT: '8080'

handlers:
  - url: /static
    static_dir: public

  - url: /.*
    script: auto
