steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Verify it runs/builds (Basic CI check)
  # This makes sure there are no syntax errors before deploying
  - name: 'node:20'
    entrypoint: 'bash'
    args: ['-c', 'node --check server.js']

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

# Timeout for the whole build
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
